version: "3.7"
services:
    nginx:
        image: nginx:1.17.3
        container_name: nginx_atividade
        ports:
            - "8080:80"
        volumes:
            - ".:/var/www/html/"
            - "./webserver/nginx.conf:/etc/nginx/nginx.conf"
        links:
            - php
    php:
        build:
            context: .
        image: phpdocker
        container_name: php_atividade
        ports:
            - "9000:9000"
        volumes:
            - ".:/var/www/html/"
